### ISSUE TITLE
ValueError: expected sequence of length 4 at dim 1 (got 0)

### ISSUE THREAD

**Issue by science64** [JannisFengler/MuZero#1]
I got this error while running the script. Thanks for doing it.

C:\Users\Predator\Desktop\DeepLearning AI\muzeroNew\muzero.py:81: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at ..\torch\csrc\utils\tensor_new.cpp:248.)
  state = torch.tensor(obs, dtype=torch.float32)
Traceback (most recent call last):
  File "C:\Users\Predator\Desktop\DeepLearning AI\muzeroNew\muzero.py", line 166, in <module>
    train()
  File "C:\Users\Predator\Desktop\DeepLearning AI\muzeroNew\muzero.py", line 153, in train
    action, mcts_policy = muzero.select_action(obs)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Predator\Desktop\DeepLearning AI\muzeroNew\muzero.py", line 81, in select_action
    state = torch.tensor(obs, dtype=torch.float32)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: expected sequence of length 4 at dim 1 (got 0)

**Comment by JannisFengler** [comment]
i reworked the whole code and this error is fixed ;)
